//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HengDaEntity
{
    using System;
    
    
    public sealed class FormMainHeader
    {
        
        private int _idx;
        
        private string _shd001;
        
        private string _shd002;
        
        private string _shd003;
        
        private string _shd004;
        
        private string _shd005;
        
        private DateTime _shd006;
        
        private string _shd007;
        
        private string _shd008;
        
        private string _shd009;
        
        private string _shd010;
        
        private string _shd011;
        
        private string _shd012;
        
        private string _shd013;
        
        private string _shd014;
        
        private string _shd015;
        
        private string _shd016;
        
        private string _shd017;
        
        private string _shd018;
        
        private string _shd019;
        
        private string _shd020;
        
        /// <summary>
        /// 编号
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string SHD001
        {
            get
            {
                return this._shd001;
            }
            set
            {
                this._shd001 = value;
            }
        }

        /// <summary>
        /// 收货单位编号
        /// </summary>

        public string SHD002
        {
            get
            {
                return this._shd002;
            }
            set
            {
                this._shd002 = value;
            }
        }

        /// <summary>
        /// 采购单号
        /// </summary>

        public string SHD003
        {
            get
            {
                return this._shd003;
            }
            set
            {
                this._shd003 = value;
            }
        }

        /// <summary>
        /// 备料单号
        /// </summary>

        public string SHD004
        {
            get
            {
                return this._shd004;
            }
            set
            {
                this._shd004 = value;
            }
        }

        /// <summary>
        /// 组别
        /// </summary>

        public string SHD005
        {
            get
            {
                return this._shd005;
            }
            set
            {
                this._shd005 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime SHD006
        {
            get
            {
                return this._shd006;
            }
            set
            {
                this._shd006 = value;
            }
        }

        /// <summary>
        /// 收货单位签章
        /// </summary>

        public string SHD007
        {
            get
            {
                return this._shd007;
            }
            set
            {
                this._shd007 = value;
            }
        }

        /// <summary>
        /// 发货人
        /// </summary>

        public string SHD008
        {
            get
            {
                return this._shd008;
            }
            set
            {
                this._shd008 = value;
            }
        }
        
        /// <summary>
        /// 审核码
        /// </summary>
                 
        public string SHD009
        {
            get
            {
                return this._shd009;
            }
            set
            {
                this._shd009 = value;
            }
        }
        
        // 
        public string SHD010
        {
            get
            {
                return this._shd010;
            }
            set
            {
                this._shd010 = value;
            }
        }
        
        // 
        public string SHD011
        {
            get
            {
                return this._shd011;
            }
            set
            {
                this._shd011 = value;
            }
        }
        
        // 
        public string SHD012
        {
            get
            {
                return this._shd012;
            }
            set
            {
                this._shd012 = value;
            }
        }
        
        // 
        public string SHD013
        {
            get
            {
                return this._shd013;
            }
            set
            {
                this._shd013 = value;
            }
        }
        
        // 
        public string SHD014
        {
            get
            {
                return this._shd014;
            }
            set
            {
                this._shd014 = value;
            }
        }
        
        // 
        public string SHD015
        {
            get
            {
                return this._shd015;
            }
            set
            {
                this._shd015 = value;
            }
        }
        
        // 
        public string SHD016
        {
            get
            {
                return this._shd016;
            }
            set
            {
                this._shd016 = value;
            }
        }
        
        // 
        public string SHD017
        {
            get
            {
                return this._shd017;
            }
            set
            {
                this._shd017 = value;
            }
        }
        
        // 
        public string SHD018
        {
            get
            {
                return this._shd018;
            }
            set
            {
                this._shd018 = value;
            }
        }
        
        // 
        public string SHD019
        {
            get
            {
                return this._shd019;
            }
            set
            {
                this._shd019 = value;
            }
        }
        
        // 
        public string SHD020
        {
            get
            {
                return this._shd020;
            }
            set
            {
                this._shd020 = value;
            }
        }
    }
}
