//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HengDaEntity
{
    using System;
    
    
    public sealed class FormMainOne
    {
        
        private int _idx;
        
        private string _she001;
        
        private string _she002;
        
        private string _she003;
        
        private string _she004;
        
        private string _she005;
        
        private string _she006;
        
        private int _she007;
        
        private decimal _she008;
        
        private string _she009;
        
        private string _she010;
        
        private string _she011;
        
        private string _she012;
        
        private string _she013;
        
        private string _she014;
        
        private string _she015;
        
        private string _she016;
        
        private string _she017;
        
        private string _she018;
        
        private string _she019;
        
        private string _she020;
        
        private string _she021;
        
        private string _she022;
        
        private string _she023;
        
        /// <summary>
        /// 编号
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string SHE001
        {
            get
            {
                return this._she001;
            }
            set
            {
                this._she001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string SHE002
        {
            get
            {
                return this._she002;
            }
            set
            {
                this._she002 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string SHE003
        {
            get
            {
                return this._she003;
            }
            set
            {
                this._she003 = value;
            }
        }

        /// <summary>
        /// 料件编号
        /// </summary>

        public string SHE004
        {
            get
            {
                return this._she004;
            }
            set
            {
                this._she004 = value;
            }
        }

        /// <summary>
        /// 款号
        /// </summary>

        public string SHE005
        {
            get
            {
                return this._she005;
            }
            set
            {
                this._she005 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string SHE006
        {
            get
            {
                return this._she006;
            }
            set
            {
                this._she006 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int SHE007
        {
            get
            {
                return this._she007;
            }
            set
            {
                this._she007 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal SHE008
        {
            get
            {
                return this._she008;
            }
            set
            {
                this._she008 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string SHE009
        {
            get
            {
                return this._she009;
            }
            set
            {
                this._she009 = value;
            }
        }
        
        // 
        public string SHE010
        {
            get
            {
                return this._she010;
            }
            set
            {
                this._she010 = value;
            }
        }
        
        // 
        public string SHE011
        {
            get
            {
                return this._she011;
            }
            set
            {
                this._she011 = value;
            }
        }
        
        // 
        public string SHE012
        {
            get
            {
                return this._she012;
            }
            set
            {
                this._she012 = value;
            }
        }
        
        // 
        public string SHE013
        {
            get
            {
                return this._she013;
            }
            set
            {
                this._she013 = value;
            }
        }
        
        // 
        public string SHE014
        {
            get
            {
                return this._she014;
            }
            set
            {
                this._she014 = value;
            }
        }
        
        // 
        public string SHE015
        {
            get
            {
                return this._she015;
            }
            set
            {
                this._she015 = value;
            }
        }
        
        // 
        public string SHE016
        {
            get
            {
                return this._she016;
            }
            set
            {
                this._she016 = value;
            }
        }
        
        // 
        public string SHE017
        {
            get
            {
                return this._she017;
            }
            set
            {
                this._she017 = value;
            }
        }
        
        // 
        public string SHE018
        {
            get
            {
                return this._she018;
            }
            set
            {
                this._she018 = value;
            }
        }
        
        // 
        public string SHE019
        {
            get
            {
                return this._she019;
            }
            set
            {
                this._she019 = value;
            }
        }
        
        // 
        public string SHE020
        {
            get
            {
                return this._she020;
            }
            set
            {
                this._she020 = value;
            }
        }
        
        // 
        public string SHE021
        {
            get
            {
                return this._she021;
            }
            set
            {
                this._she021 = value;
            }
        }
        
        // 
        public string SHE022
        {
            get
            {
                return this._she022;
            }
            set
            {
                this._she022 = value;
            }
        }
        
        // 
        public string SHE023
        {
            get
            {
                return this._she023;
            }
            set
            {
                this._she023 = value;
            }
        }
    }
}
