//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HengDaEntity
{
    using System;
    
    
    public sealed class FormMainTwo
    {
        
        private int _idx;
        
        private string _shf001;
        
        private string _shf002;
        
        private string _shf003;
        
        private int _shf004;
        
        private decimal _shf005;
        
        private int _shf006;
        
        private string _shf007;
        
        private string _shf008;
        
        private string _shf009;
        
        private string _shf010;
        
        private string _shf011;
        
        private string _shf012;
        
        private string _shf013;
        
        private string _shf014;
        
        private string _shf015;
        
        private string _shf016;
        
        private string _shf017;
        
        private string _shf018;
        
        private string _shf019;
        
        private string _shf020;
        
        /// <summary>
        /// 编号
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string SHF001
        {
            get
            {
                return this._shf001;
            }
            set
            {
                this._shf001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string SHF002
        {
            get
            {
                return this._shf002;
            }
            set
            {
                this._shf002 = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string SHF003
        {
            get
            {
                return this._shf003;
            }
            set
            {
                this._shf003 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int SHF004
        {
            get
            {
                return this._shf004;
            }
            set
            {
                this._shf004 = value;
            }
        }

        /// <summary>
        /// 厚度
        /// </summary>

        public decimal SHF005
        {
            get
            {
                return this._shf005;
            }
            set
            {
                this._shf005 = value;
            }
        }

        /// <summary>
        /// 密度
        /// </summary>

        public int SHF006
        {
            get
            {
                return this._shf006;
            }
            set
            {
                this._shf006 = value;
            }
        }

        /// <summary>
        /// 名称
        /// </summary>

        public string SHF007
        {
            get
            {
                return this._shf007;
            }
            set
            {
                this._shf007 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string SHF008
        {
            get
            {
                return this._shf008;
            }
            set
            {
                this._shf008 = value;
            }
        }
        
        // 
        public string SHF009
        {
            get
            {
                return this._shf009;
            }
            set
            {
                this._shf009 = value;
            }
        }
        
        // 
        public string SHF010
        {
            get
            {
                return this._shf010;
            }
            set
            {
                this._shf010 = value;
            }
        }
        
        // 
        public string SHF011
        {
            get
            {
                return this._shf011;
            }
            set
            {
                this._shf011 = value;
            }
        }
        
        // 
        public string SHF012
        {
            get
            {
                return this._shf012;
            }
            set
            {
                this._shf012 = value;
            }
        }
        
        // 
        public string SHF013
        {
            get
            {
                return this._shf013;
            }
            set
            {
                this._shf013 = value;
            }
        }
        
        // 
        public string SHF014
        {
            get
            {
                return this._shf014;
            }
            set
            {
                this._shf014 = value;
            }
        }
        
        // 
        public string SHF015
        {
            get
            {
                return this._shf015;
            }
            set
            {
                this._shf015 = value;
            }
        }
        
        // 
        public string SHF016
        {
            get
            {
                return this._shf016;
            }
            set
            {
                this._shf016 = value;
            }
        }
        
        // 
        public string SHF017
        {
            get
            {
                return this._shf017;
            }
            set
            {
                this._shf017 = value;
            }
        }
        
        // 
        public string SHF018
        {
            get
            {
                return this._shf018;
            }
            set
            {
                this._shf018 = value;
            }
        }
        
        // 
        public string SHF019
        {
            get
            {
                return this._shf019;
            }
            set
            {
                this._shf019 = value;
            }
        }
        
        // 
        public string SHF020
        {
            get
            {
                return this._shf020;
            }
            set
            {
                this._shf020 = value;
            }
        }
    }
}
